config/routes.rb
ExquisiteCorpse::Application.routes.draw do
  resources :corpses

  root to: "body_parts#index"
  resources :body_parts

end

app/models/body_part.rb
class BodyPart < ActiveRecord::Base
  belongs_to :corpse
  attr_accessible :image
end

app/models/corpse.rb
class Corpse < ActiveRecord::Base
  has_many :body_parts

  def head
  	body_parts.where(name: "head").first
  end

  def torso
  	body_parts.where(name: "torso").first
  end

  def legs
    body_parts.where(name: "legs").first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/body_part_controller.rb
class BodyPartController < ApplicationController
  def new
  	@body_part = BodyPart.new
  	render :new
  end

  def save
  end

  def display
  end
end

app/controllers/body_parts_controller.rb
class BodyPartsController < ApplicationController
  # GET /body_parts
  # GET /body_parts.json
  def index
    @body_parts = BodyPart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @body_parts }
    end
  end

  # GET /body_parts/1
  # GET /body_parts/1.json
  def show
    @body_part = BodyPart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @body_part }
    end
  end

  # GET /body_parts/new
  # GET /body_parts/new.json
  def new
    @body_part = BodyPart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @body_part }
    end
  end

  # GET /body_parts/1/edit
  def edit
    @body_part = BodyPart.find(params[:id])
  end

  # POST /body_parts
  # POST /body_parts.json
  def create
    @body_part = BodyPart.new(params[:body_part])

    respond_to do |format|
      if @body_part.save
        format.html { redirect_to @body_part, notice: 'Body part was successfully created.' }
        format.json { render json: @body_part, status: :created, location: @body_part }
      else
        format.html { render action: "new" }
        format.json { render json: @body_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /body_parts/1
  # PUT /body_parts/1.json
  def update
    @body_part = BodyPart.find(params[:id])

    respond_to do |format|
      if @body_part.update_attributes(params[:body_part])
        format.html { redirect_to @body_part, notice: 'Body part was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @body_part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /body_parts/1
  # DELETE /body_parts/1.json
  def destroy
    @body_part = BodyPart.find(params[:id])
    @body_part.destroy

    respond_to do |format|
      format.html { redirect_to body_parts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/corpses_controller.rb
class CorpsesController < ApplicationController
  # GET /corpses
  # GET /corpses.json
  def index
    @corpses = Corpse.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @corpses }
    end
  end

  # GET /corpses/1
  # GET /corpses/1.json
  def show
    @corpse = Corpse.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @corpse }
    end
  end

  # GET /corpses/new
  # GET /corpses/new.json
  def new
    @corpse = Corpse.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @corpse }
    end
  end

  # GET /corpses/1/edit
  def edit
    @corpse = Corpse.find(params[:id])
  end

  # POST /corpses
  # POST /corpses.json
  def create
    @corpse = Corpse.new(params[:corpse])

    respond_to do |format|
      if @corpse.save
        format.html { redirect_to @corpse, notice: 'Corpse was successfully created.' }
        format.json { render json: @corpse, status: :created, location: @corpse }
      else
        format.html { render action: "new" }
        format.json { render json: @corpse.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /corpses/1
  # PUT /corpses/1.json
  def update
    @corpse = Corpse.find(params[:id])

    respond_to do |format|
      if @corpse.update_attributes(params[:corpse])
        format.html { redirect_to @corpse, notice: 'Corpse was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @corpse.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /corpses/1
  # DELETE /corpses/1.json
  def destroy
    @corpse = Corpse.find(params[:id])
    @corpse.destroy

    respond_to do |format|
      format.html { redirect_to corpses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/body_part_helper.rb
module BodyPartHelper
end

app/helpers/body_parts_helper.rb
module BodyPartsHelper
end

app/helpers/corpses_helper.rb
module CorpsesHelper
end

app/views/body_part/display.html.erb
<h1>BodyPart#display</h1>
<p>Find me in app/views/body_part/display.html.erb</p>

app/views/body_part/new.html.erb
<canvas id="drawing" width="500" height="200"></canvas>

<%= form_for @body_part do |f| %>
  <%= f.hidden_field :image %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

<button id="clear">Clear</button>

app/views/body_part/save.html.erb
<h1>Saved!</h1>

app/views/body_parts/_form.html.erb
<canvas id="drawing" width="500" height="200"></canvas>

<%= form_for(@body_part) do |f| %>
  <%= f.hidden_field :image %>

  <% if @body_part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@body_part.errors.count, "error") %> prohibited this body_part from being saved:</h2>

      <ul>
      <% @body_part.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<button id="clear">Clear</button>

app/views/body_parts/edit.html.erb
<h1>Editing body_part</h1>

<%= render 'form' %>

<%= link_to 'Show', @body_part %> |
<%= link_to 'Back', body_parts_path %>

app/views/body_parts/index.html.erb
<h1>Draw Body Parts or else</h1>

<table>
  <tr>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @body_parts.each do |body_part| %>
  <tr>
    <td><img src="<%= body_part.image %>" /></td>
    <td><%= link_to 'Show', body_part %></td>
    <td><%= link_to 'Edit', edit_body_part_path(body_part) %></td>
    <td><%= link_to 'Destroy', body_part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Body part', new_body_part_path %>

app/views/body_parts/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', body_parts_path %>

app/views/body_parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Image:</b>
  <img src="<%= @body_part.image %>" />
</p>


<%= link_to 'Edit', edit_body_part_path(@body_part) %> |
<%= link_to 'Back', body_parts_path %>

app/views/corpses/_form.html.erb
<%= form_for(@corpse) do |f| %>
  <% if @corpse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@corpse.errors.count, "error") %> prohibited this corpse from being saved:</h2>

      <ul>
      <% @corpse.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :head %><br />
    <%= f.text_field :head %>
  </div>
  <div class="field">
    <%= f.label :torso %><br />
    <%= f.text_field :torso %>
  </div>
  <div class="field">
    <%= f.label :legs %><br />
    <%= f.text_field :legs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/corpses/edit.html.erb
<h1>Editing corpse</h1>

<%= render 'form' %>

<%= link_to 'Show', @corpse %> |
<%= link_to 'Back', corpses_path %>

app/views/corpses/index.html.erb
<h1>Listing corpses</h1>

<table>
  <tr>
    <th>Head</th>
    <th>Torso</th>
    <th>Legs</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @corpses.each do |corpse| %>
  <tr>
    <td><img src="<%= corpse.head.image %>"></td>
    <td><img src="<%= corpse.torso.image %>"></td>
    <td><img src="<%= corpse.legs.image %>"></td>
    <td><%= link_to 'Show', corpse %></td>
    <td><%= link_to 'Edit', edit_corpse_path(corpse) %></td>
    <td><%= link_to 'Destroy', corpse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Corpse', new_corpse_path %>

app/views/corpses/new.html.erb
<h1>New corpse</h1>

<%= render 'form' %>

<%= link_to 'Back', corpses_path %>

app/views/corpses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Head:</b>
  <%= @corpse.head %>
</p>

<p>
  <b>Torso:</b>
  <%= @corpse.torso %>
</p>

<p>
  <b>Legs:</b>
  <%= @corpse.legs %>
</p>


<%= link_to 'Edit', edit_corpse_path(@corpse) %> |
<%= link_to 'Back', corpses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExquisiteCorpse</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<!--<body class="<%= controller_name %> <%= action_name %>">-->
<body>
	<div class="row">
		<div class="span4 <%= controller_name %> <%= action_name %>"></div>
		<div class="span4" id="drawings_target"></div>
	</div>



<%= yield %>


</body>
</html>